set up ci and ci_teardown

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -10,6 +10,8 @@ jobs:
     runs-on: ubuntu-latest
     
     env:
+      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
+      GCLOUD_STORAGE_PATH_MANIFEST: ${{ secrets.GCLOUD_STORAGE_PATH_MANIFEST }}
       DEV_BIGQUERY_PROJECT: ${{ secrets.DEV_BIGQUERY_PROJECT }}
       DEV_BIGQUERY_DATASET: ${{ secrets.DEV_BIGQUERY_DATASET }}
       PROD_BIGQUERY_PROJECT: ${{ secrets.PROD_BIGQUERY_PROJECT }}
@@ -37,6 +39,20 @@ jobs:
     - name: Install dependencies
       run: pip install -r requirements.txt
     
+    - name: Authenticate to Google Cloud
+      uses: google-github-actions/auth@v0.4.3
+      with:
+        credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
+    
+    - name: Set up Cloud SDK
+      uses: google-github-actions/setup-gcloud@v1
+      with:
+        project_id: ${{ secrets.DEV_BIGQUERY_PROJECT }}
+    
+    - name: Copy manifest.json from Google Cloud Storage
+      run: |
+        gsutil cp gs://${{ env.GCLOUD_STORAGE_PATH_MANIFEST }}/manifest.json ./ || echo "Manifest not found"
+    
     - name: Get Schema ID
       id: schema_id
       run: echo "SCHEMA_ID=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
@@ -55,4 +71,8 @@ jobs:
     
     - name: Run dbt build
       run: |
-        dbt run -s stg_new_address --profiles-dir dbt_project --project-dir dbt_project --target pr --vars "schema_id: $SCHEMA_ID"
+        if [ -f "./manifest.json" ]; then
+          dbt run -s 'state:modified+' --defer --state ./ --profiles-dir dbt_project --project-dir dbt_project --target pr --vars "schema_id: $SCHEMA_ID"
+        else
+          dbt run --profiles-dir dbt_project --project-dir dbt_project --target pr --vars "schema_id: $SCHEMA_ID"
+        fi
